# Generated by Django 2.2.10 on 2021-06-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alternative_flow',
            fields=[
                ('id_alternativeflow', models.AutoField(primary_key=True, serialize=False)),
                ('nama_alternative', models.CharField(max_length=200)),
                ('postcondition_alternative', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField(default=0)),
                ('nama_project', models.CharField(max_length=50)),
                ('datecreated', models.DateTimeField()),
                ('dateaccessed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='usecase',
            fields=[
                ('id_usecase', models.AutoField(primary_key=True, serialize=False)),
                ('nama_usecase', models.CharField(max_length=20)),
                ('brief_description', models.CharField(max_length=300)),
                ('precondition', models.CharField(max_length=100)),
                ('postcondition', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=20)),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='step_basic',
            fields=[
                ('id_step_basic', models.AutoField(primary_key=True, serialize=False)),
                ('step_value', models.CharField(max_length=1000)),
                ('step_actor_basic', models.CharField(max_length=20)),
                ('id_usecase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usecase')),
            ],
        ),
        migrations.CreateModel(
            name='step_alternative_flow',
            fields=[
                ('id_step_alternative', models.AutoField(primary_key=True, serialize=False)),
                ('step_value', models.CharField(max_length=1000)),
                ('id_alternativeflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alternative_flow')),
            ],
        ),
        migrations.AddField(
            model_name='alternative_flow',
            name='id_step_basic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.step_basic'),
        ),
        migrations.AddField(
            model_name='alternative_flow',
            name='id_usecase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usecase'),
        ),
        migrations.CreateModel(
            name='activity_diagram',
            fields=[
                ('id_activity', models.AutoField(primary_key=True, serialize=False)),
                ('nama_activity', models.CharField(max_length=50)),
                ('id_usecase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usecase')),
            ],
        ),
    ]
