# Generated by Django 2.2.10 on 2021-05-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basic_flow',
            fields=[
                ('id_basicflow', models.AutoField(primary_key=True, serialize=False)),
                ('steps_basicflow', models.CharField(max_length=1000)),
                ('postcondition_basic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField(default=0)),
                ('nama_project', models.CharField(max_length=50)),
                ('datecreated', models.DateTimeField()),
                ('dateaccessed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='usecase',
            fields=[
                ('id_usecase', models.AutoField(primary_key=True, serialize=False)),
                ('nama_usecase', models.CharField(max_length=20)),
                ('brief_description', models.CharField(default='Add Description Here', max_length=300)),
                ('precondition', models.CharField(max_length=100)),
                ('primary_actor', models.CharField(max_length=20)),
                ('secondary_actor', models.CharField(max_length=20)),
                ('dependency', models.CharField(default='Add Value Here', max_length=30)),
                ('generalization', models.CharField(default='Add Value Here', max_length=30)),
                ('id_basicflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.basic_flow')),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.AddField(
            model_name='basic_flow',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
        migrations.CreateModel(
            name='alternative_flow',
            fields=[
                ('id_alternativeflow', models.AutoField(primary_key=True, serialize=False)),
                ('type_alternativeflow', models.CharField(max_length=30)),
                ('rfs', models.FloatField(max_length=8)),
                ('steps_alternativeflow', models.CharField(max_length=1000)),
                ('postcondition_alternative', models.CharField(max_length=100)),
                ('id_basicflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.basic_flow')),
                ('id_usecase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usecase')),
            ],
        ),
        migrations.CreateModel(
            name='activity_diagram',
            fields=[
                ('id_activity', models.AutoField(primary_key=True, serialize=False)),
                ('nama_activity', models.CharField(max_length=50)),
                ('datecreated', models.DateTimeField()),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
    ]
