# Generated by Django 2.2.10 on 2021-05-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usecase',
            fields=[
                ('id_usecase', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nama_user', models.CharField(max_length=20)),
                ('email_user', models.EmailField(max_length=254)),
                ('password_user', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('nama_project', models.CharField(max_length=50)),
                ('datecreated', models.DateTimeField()),
                ('dateaccessed', models.DateTimeField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='activity_diagram',
            fields=[
                ('id_activity', models.AutoField(primary_key=True, serialize=False)),
                ('nama_activity', models.CharField(max_length=50)),
                ('datecreated', models.DateTimeField()),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
    ]
