# Generated by Django 2.2.10 on 2021-06-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_basic',
            name='rule',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
