# Generated by Django 2.2.10 on 2021-06-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_alternative_flow',
            name='condition',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
