# Generated by Django 2.2.10 on 2021-06-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='brief_description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='dependency',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='generalization',
            field=models.CharField(max_length=30),
        ),
    ]
