# Generated by Django 2.2.10 on 2021-06-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_alternative_flow',
            name='step_actor_alternative',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
