# Generated by Django 2.2.10 on 2021-05-20 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='brief_description',
            field=models.CharField(default='Add Description Here', max_length=300),
        ),
        migrations.AddField(
            model_name='usecase',
            name='dependency',
            field=models.CharField(default='Add Value Here', max_length=30),
        ),
        migrations.AddField(
            model_name='usecase',
            name='generalization',
            field=models.CharField(default='Add Value Here', max_length=30),
        ),
        migrations.AddField(
            model_name='usecase',
            name='id_project',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='app.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usecase',
            name='nama_usecase',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usecase',
            name='precondition',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usecase',
            name='primary_actor',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usecase',
            name='secondary_actor',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='basic_flow',
            fields=[
                ('id_basicflow', models.AutoField(primary_key=True, serialize=False)),
                ('steps_basicflow', models.CharField(max_length=1000)),
                ('postcondition_basic', models.CharField(max_length=100)),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='alternative_flow',
            fields=[
                ('id_alternativeflow', models.AutoField(primary_key=True, serialize=False)),
                ('type_alternativeflow', models.CharField(max_length=30)),
                ('rfs', models.FloatField(max_length=8)),
                ('steps_alternativeflow', models.CharField(max_length=1000)),
                ('postcondition_alternative', models.CharField(max_length=100)),
                ('id_basicflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.basic_flow')),
                ('id_usecase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usecase')),
            ],
        ),
        migrations.AddField(
            model_name='usecase',
            name='id_basicflow',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='app.basic_flow'),
            preserve_default=False,
        ),
    ]
