# Generated by Django 2.2.10 on 2021-06-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_step_alternative_flow_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_if',
            name='step_actor_false',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step_if',
            name='step_actor_true',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
