# Generated by Django 2.2.10 on 2021-06-26 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_step_if_id_usecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_if',
            name='id_usecase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.usecase'),
            preserve_default=False,
        ),
    ]
