# Generated by Django 2.2.10 on 2021-06-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210610_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='step_alternative_flow',
            fields=[
                ('id_step_alternative', models.AutoField(primary_key=True, serialize=False)),
                ('step_value', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='step_basic',
            fields=[
                ('id_step_basic', models.AutoField(primary_key=True, serialize=False)),
                ('step_value', models.CharField(max_length=1000)),
                ('id_basicflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.basic_flow')),
            ],
        ),
        migrations.RenameField(
            model_name='alternative_flow',
            old_name='type_alternativeflow',
            new_name='type_flow',
        ),
        migrations.RemoveField(
            model_name='activity_diagram',
            name='datecreated',
        ),
        migrations.RemoveField(
            model_name='activity_diagram',
            name='id_project',
        ),
        migrations.RemoveField(
            model_name='alternative_flow',
            name='id_basicflow',
        ),
        migrations.RemoveField(
            model_name='alternative_flow',
            name='steps_alternativeflow',
        ),
        migrations.AddField(
            model_name='activity_diagram',
            name='id_usecase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.usecase'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='step',
        ),
        migrations.AddField(
            model_name='step_alternative_flow',
            name='id_alternativeflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alternative_flow'),
        ),
    ]
