# Generated by Django 2.2.10 on 2021-06-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_step_alternative_flow_step_actor_alternative'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_alternative_flow',
            name='id_step_basic',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='app.step_basic'),
            preserve_default=False,
        ),
    ]
