# Generated by Django 2.2.10 on 2021-06-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210610_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step_basic',
            name='id_basicflow',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='dependency',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='generalization',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='primary_actor',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='secondary_actor',
        ),
        migrations.AddField(
            model_name='step_basic',
            name='id_usecase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.usecase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usecase',
            name='actor',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='basic_flow',
        ),
    ]
