# Generated by Django 2.2.10 on 2021-06-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_step_alternative_flow_id_step_basic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step_alternative_flow',
            old_name='step_value',
            new_name='step_alternavie',
        ),
    ]
