# Generated by Django 2.2.10 on 2021-06-10 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210610_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative_flow',
            name='rfs',
        ),
        migrations.AddField(
            model_name='alternative_flow',
            name='id_step_basic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.step_basic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usecase',
            name='postcondition',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
