# Generated by Django 2.2.10 on 2021-06-15 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_step_alternative_flow_id_usecase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step_alternative_flow',
            name='id_alternativeflow',
        ),
    ]
