# Generated by Django 2.2.10 on 2021-06-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210611_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative_flow',
            name='type_flow',
        ),
    ]
