# Generated by Django 2.2.10 on 2021-06-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_step_alternative_flow_id_alternativeflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative_flow',
            name='id_usecase',
        ),
    ]
