# Generated by Django 2.2.10 on 2021-06-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_alternative_flow_id_usecase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step_alternative_flow',
            old_name='step_alternavie',
            new_name='step_alternative',
        ),
    ]
